version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin123@cluster0.budo6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=asdfghjkrtyurtyurtyuj
      - CLIENT_URL=http://localhost:5173